snapd/spread-venv: use yq, which keeps the item order
Signed-off-by: Maciek Borzecki <maciek.borzecki@gmail.com>

diff --git a/snapd/spread-venv b/snapd/spread-venv
--- a/snapd/spread-venv
+++ b/snapd/spread-venv
@@ -6,8 +6,8 @@ if [ -n "${D-}" ]; then
     set -x
 fi
 
-if ! command -v gojq >/dev/null 2>&1; then
-    echo "gojq not found in PATH"
+if ! command -v yq >/dev/null 2>&1; then
+    echo "yq not found in PATH"
     exit 1
 fi
 
@@ -48,12 +48,9 @@ set -e
 cd '"$PWD"'
 cp -v spread.yaml spread.yaml.tmp
 if [ -d spread-layers ]; then
-    find spread-layers/ -type f -o -type l | while read -r n; do
-        echo "-- merging $n"
-        gojq -s --yaml-output --yaml-input '\''.[0] * .[1]'\'' \
-            spread.yaml.tmp "$n" > spread.yaml.tmp.1
-        mv -v spread.yaml.tmp.1 spread.yaml.tmp
-    done
+    layers="$(find spread-layers/ -type f -o -type l | sort)"
+    echo "-- merging layers: $layers"
+    yq ea  '\''. as $item ireduce ({}; . * $item )'\'' spread.yaml $layers > spread.yaml.tmp
 else
     echo "-- no spread-layers directory"
 fi
